g.clear();
g.setColor(255,0,0);
g.fillRect(0, 20, 88, 100);
g.setColor(0,0,255);
g.fillRect(88, 20, 200, 100);
g.setColor(0,255,0);
g.fillRect(88, 100, 200, 200);
g.setColor(255,255,0);
g.fillRect(0, 100, 88, 200);


Bangle.on('touch', function(button, xy) {
  if (xy.x < 88 && xy.y < 100) {
    print("button up/left "+xy.x+" "+xy.y);
  } else if (xy.x < 88 && xy.y > 100) {
    print("button down/left "+xy.x+" "+xy.y);
  } else if (xy.x > 88 && xy.y < 100) {
    print("button up/right "+xy.x+" "+xy.y);
  } else if (xy.x > 88 && xy.y > 100) {
    print("button down/right "+xy.x+" "+xy.y);
  } else {
  print("x/y "+xy.x+" "+xy.y); }});

var img = require("heatshrink").decompress(atob("lElwIJGgf8AgUEg+AAgU88AECgcYAgMH4HMBIU4gYEBhEOgAZBhEDwFAgEZ4HAkEAiUgmEQgE0iEYhEAkkRw0EgFkiGDg0Ao0ggOCgHD4EA50A2AzBuMAyED8kxgMQoUkAgMAokQsUCAgMg4wEBgdjhkGnkBx0wggNBnHAAgNwsZTBolBxgEBtkBmEAiE4gQ8BiUA8ZsBkMA2QEBkEe+QEBoF2yQEBoOOAgXOmYECuPBD4MAv0AjyvDhgCBA"));
g.drawImage(img,0,20);

var img2 = E.toArrayBuffer(atob("KBaCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVVVAABVVQAAAEAAAFVVQABAAABAAAAAAAAAVAAVVVVVVVVVVQFAUAEAEAEAFAAAUEAUVVUFUUFVQBBAAAQAUBQAAABQQBVVVVVFVVUBQBBQAAAAAAAAVAAFAAAAAAAAABAAAQAAAAAAAAAQAAEQAAAAAAAAEAABBAAAAAAAABAAAEUAAAAAAABAAABQVAAAAAABQAAAFAAAAAAAFAAAAAFUAAAABUAAAAAAAVVVVUAAAAAAAAAAAAAAAAAA="));
g.drawImage(img2,88,40);

var img3 = E.toArrayBuffer(atob("KCyCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFVQAAAAAAAAVUBAEFAAAAAAAEBVQBRFUAAAAABAQEBVQBAAAAFRVEBVUEBVEAAUEQRAQFBAQVUAEAUEQEBQQEBBQBAFBEBAQEBAQEAQBQQQQEBBQEEABAUEEEBAQUBBAAQBBBBAQUFAQQAEAQQRAQEBQEQABAEEEQEBBUFEABVVVVVVVVVVVAAQAAAAAAAAABUAEAAAAAAAAAABABAAAAAAAAAAAQAQAAAAAAAAAAEAEAAAAAAAAAABABAAAFVVVUAAAAAQAAFAAABUAAQAEAAEAAAABQAEABAAFAAAAAEABAAEABAAAAAAQAQABAARAAAAAEAEAAQAEQAAAABABAAEABEAAAAAQAQABAARAAAAAUAEAAQAEEAAAAEAAAAEAAQAAAAEABAAAQABQAAAFAAQAAEAABVVVUAAEAABAAAAAAAAABAAAQAAAAAAAAAQAAFAAAAAAAAAQAAAQAAAAAAAAEAAAEAAAAAAAAFAAABQAAAAAAABAAAAFUAAAAAAFAAAAAFVVVVVVUAAAAAAAAAAAAAAAA"));
g.drawImage(img3,88,100);

var img4 = E.toArrayBuffer(atob("KCeCAAAAAAAAAAAAAAAAAAAVVVUAAAAAAAABQAAAFAAAAAAAFAAAEAFAAAAAAEAAAAAAFAAAAAEAAAAAEAEAAAAEAAAAAAAAQAAAEBAUAQEAABAAAFAAAAAAAAAEAABAAAAAAAAAAQABAAAAAAAAAAEAAQAAAAAAAAAAQAQUAAAAAAAAAEAEEAAAAAAAAABABEAAAAAAAAAAEARAAAAAAAAAABAEUAAAAAAAAABQBAAAAAAAAAAAQAFAAAAAAAAAFUAEBVVVVVVVVUAQEAAAAAAAAAAABBAAAEAAAAAAFVAVUAVVVUABVVFAARVQBQAVVAEBAAFFQAAAAAAAAQAAQAAAAAAAABQAAVVVVQFVVVVVQAUAAABQAAAAAEAEAAAAAAAAAAAQBAAAAAAAAAAAEAQAAAAAAAAAAEAFAAAAAAAAAAFAAFVVVVVVVVVUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="));
g.drawImage(img4,0,100);


